# Generated by Django 3.2.9 on 2021-12-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0031_auto_20211204_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
