# Generated by Django 3.2.9 on 2021-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0036_auto_20211204_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking',
            field=models.TextField(default='', verbose_name='Инструкция по приготовлению'),
            preserve_default=False,
        ),
    ]
