# Generated by Django 3.2.9 on 2021-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0020_auto_20211203_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
