# Generated by Django 3.2.9 on 2021-12-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0023_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
