# Generated by Django 3.2.9 on 2021-12-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0025_recipe_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('image_path', models.ImageField(upload_to='.\\images')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='alcohol',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='TankAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('allocation', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.drink')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredient',
            field=models.ManyToManyField(related_name='mischung', through='recipe_app.IngredientRatio', to='recipe_app.Ingredient'),
        ),
    ]
