# Generated by Django 3.2.9 on 2021-12-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0029_auto_20211204_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
