# Generated by Django 3.2.9 on 2021-12-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0035_recipe_gram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='gram',
            field=models.TextField(max_length=300, verbose_name='Укажите кол-во грамм, шт или мл. Каждого инградиента'),
        ),
    ]
