# Generated by Django 3.2.9 on 2021-12-04 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0038_auto_20211205_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='gram',
        ),
        migrations.AddField(
            model_name='recipe',
            name='gramm',
            field=models.TextField(default='', max_length=300, verbose_name='Укажите кол-во грамм, шт или мл. Каждого инградиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.category', verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
