# Generated by Django 3.2.9 on 2021-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0040_rename_gramm_recipe_gram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_title',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
