# Generated by Django 3.2.9 on 2021-12-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0041_auto_20211205_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_title',
        ),
    ]
