# Generated by Django 3.2.9 on 2021-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0042_rename_name_ingredient_ingredient_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='url',
            field=models.SlugField(default='', max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
