# Generated by Django 3.2.9 on 2021-12-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0043_ingredient_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='url',
        ),
    ]
