# Generated by Django 3.2.9 on 2021-12-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0045_recipe_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='complete',
        ),
    ]
