# Generated by Django 3.2.9 on 2021-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0049_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
