# Generated by Django 3.2.9 on 2021-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0052_auto_20211209_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatar/', verbose_name='Аватарка'),
        ),
    ]
