# Generated by Django 3.2.9 on 2021-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0054_alter_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
