# Generated by Django 3.2.9 on 2021-12-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0055_auto_20211209_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
