# Generated by Django 3.2.9 on 2021-12-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0056_recipe_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='avatar',
        ),
    ]
