# Generated by Django 3.2.9 on 2021-12-08 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0057_remove_recipe_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
