# Generated by Django 3.2.9 on 2021-12-08 22:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0059_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(max_length=30, verbose_name=django.contrib.auth.models.User),
        ),
    ]
