# Generated by Django 3.2.9 on 2021-12-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0060_alter_avatar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='name',
        ),
    ]
