# Generated by Django 3.2.9 on 2021-12-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0061_remove_avatar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='gender',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='location',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
