# Generated by Django 3.2.9 on 2021-12-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0062_auto_20211209_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='location',
        ),
    ]
