# Generated by Django 3.2.9 on 2021-12-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0063_auto_20211209_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепты', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
