# Generated by Django 3.2.9 on 2021-12-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0065_cereal_flour_nutsdriedfruit_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Мясо',
                'verbose_name_plural': 'Мясо',
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Овощи',
                'verbose_name_plural': 'Овощи',
            },
        ),
    ]
