# Generated by Django 3.2.9 on 2021-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0066_meat_vegetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create',
            field=models.DateTimeField(),
        ),
    ]
