# Generated by Django 3.2.9 on 2021-12-19 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0067_alter_recipe_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAreaList',
            fields=[
                ('avatar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipe_app.avatar')),
            ],
            bases=('recipe_app.avatar', django.views.generic.list.ListView),
        ),
    ]
