# Generated by Django 3.2.9 on 2021-12-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0068_personalarealist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='Meat', to='recipe_app.Ingredient', verbose_name='Ингредианты'),
        ),
        migrations.DeleteModel(
            name='PersonalAreaList',
        ),
    ]
