# Generated by Django 3.2.9 on 2021-12-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0069_auto_20211221_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cereal',
        ),
        migrations.DeleteModel(
            name='Flour',
        ),
        migrations.DeleteModel(
            name='Meat',
        ),
        migrations.DeleteModel(
            name='NutsDriedFruit',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='recipe_app.Ingredient', verbose_name='Ингредианты'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
